<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyTitle>Drone Surveillance AI System</AssemblyTitle>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseDatabase.net" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.118" />
    <PackageReference Include="Websocket.Client" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Data\" />
  </ItemGroup>
  <ItemGroup>
  <Resource Include="Images\logo.png" />
  <Resource Include="Images\connect drone.png" />
  <Resource Include="Images\Monitor Drone.png" />
  <Resource Include="Images\Track Drone.png" />  
  </ItemGroup>

</Project>
